window.plugins = [
    {
        name: 'clouddisk',
        path: 'plugins/cloud-disk/index.js',
        url: './plugins/cloud-disk/index.js',
        url_nodejs: './cloud-disk/index.js',
        index: 'clouddisk_c',
        desc: 'cloud disk api plugin',
        author: 'poplang',
        date: '2023-6-27',
        nodejs: true,
        browser: true,
    },
    {
        name: 'pop.form.engine',
        path: 'plugins/formengine/index.js',
        url: './plugins/formengine/index.js',
        url_nodejs: './formengine/index.js',
        index: 'formengine_c',
        desc: 'form-engine api plugin',
        author: 'poplang',
        date: '2023-9-20',
        nodejs: true,
        browser: true,
    },
    {
        name: 'os.system.cmd',
        path: 'plugins/systemcmd/index.js',
        url: './plugins/systemcmd/index.js',
        url_nodejs: './systemcmd/index.js',
        index: 'systemcmd_c',
        desc: 'system cmd api plugin',
        author: 'poplang',
        date: '2023-9-20',
        nodejs: true,
        browser: false,
    },
    {
        name: 'pop.location',
        path: 'plugins/location/index.js',
        url: './plugins/location/index.js',
        url_nodejs: './location/index.js',
        index: 'location_c',
        desc: 'location api plugin',
        author: 'poplang',
        date: '2023-10-20',
        nodejs: true,
        browser: false,
    },
    {
        name: 'fintechsdk',
        path: 'plugins/fintechsdk/index2.js',
        url: './plugins/fintechsdk/index2.js',
        url_nodejs: './fintechsdk/index2.js',
        index: 'fintechsdk_c',
        desc: 'fintechsdk api plugin',
        author: 'fintechsdk',
        date: '2023-12-6',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtchannel',
        path: 'plugins/rt-channel/index.js',
        url: './plugins/rt-channel/index.js',
        url_nodejs: './rt-channel/index.js',
        index: 'rtchannel_c',
        desc: 'rtchannel api plugin',
        author: 'rtchannel',
        date: '2023-12-8',
        nodejs: true,
        browser: true,
    }
    ,
    {
        name: 'rtmarket',
        path: 'plugins/rt-market/index.js',
        url: './plugins/rt-market/index.js',
        url_nodejs: './rt-market/index.js',
        index: 'rtmarket_c',
        desc: 'rtmarket api plugin',
        author: 'rtmarket',
        date: '2023-12-12',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtstandard',
        path: 'plugins/rt-market-standard/index.js',
        url: './plugins/rt-market-standard/index.js',
        url_nodejs: './rt-market-standard/index.js',
        index: 'rtstandard_c',
        desc: 'rtstandard api plugin',
        author: 'rtmarket',
        date: '2023-12-20',
        nodejs: true,
        browser: true,
    },
    {
        name: 'monitor',
        path: 'plugins/monitor/index.js',
        url: './plugins/monitor/index.js',
        url_nodejs: './monitor/index.js',
        index: 'monitor_c',
        desc: 'monitor api plugin',
        author: 'poplang',
        date: '2023-12-29',
        nodejs: true,
        browser: true,
    },
    {
        name: 'captcha',
        path: 'plugins/captcha/index.js',
        url: './plugins/captcha/index.js',
        url_nodejs: './captcha/index.js',
        index: 'captcha_c',
        desc: 'captcha api plugin',
        author: 'poplang',
        date: '2023-12-28',
        nodejs: true,
        browser: true,
    },
    {
        name: 'msgbottle',
        path: 'plugins/rt-msgbottle/index.js',
        url: './plugins/rt-msgbottle/index.js',
        url_nodejs: './rt-msgbottle/index.js',
        index: 'rtmsgbottle_c',
        desc: 'rtmsgbottle api plugin',
        author: 'poplang',
        date: '2024-1-3',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtcode',
        path: 'plugins/rt-code/index.js',
        url: './plugins/rt-code/index.js',
        url_nodejs: './rt-code/index.js',
        index: 'rtcode_c',
        desc: 'rtcode api plugin',
        author: 'poplang',
        date: '2024-1-6',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtshopping',
        path: 'plugins/rt-shopping/index.js',
        url: './plugins/rt-shopping/index.js',
        url_nodejs: './rt-shopping/index.js',
        index: 'rtshopping_c',
        desc: 'rtshopping api plugin',
        author: 'poplang',
        date: '2024-1-8',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtchess',
        path: 'plugins/rt-chess/index.js',
        url: './plugins/rt-chess/index.js',
        url_nodejs: './rt-chess/index.js',
        index: 'rtchess_c',
        desc: 'rtchess api plugin',
        author: 'poplang',
        date: '2024-1-22',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtaudioroom',
        path: 'plugins/rt-audioroom/index.js',
        url: './plugins/rt-audioroom/index.js',
        url_nodejs: './rt-audioroom/index.js',
        index: 'rtaudioroom_c',
        desc: 'rtaudioroom api plugin',
        author: 'poplang',
        date: '2024-1-30',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtvideoroom',
        path: 'plugins/rt-videoroom/index.js',
        url: './plugins/rt-videoroom/index.js',
        url_nodejs: './rt-videoroom/index.js',
        index: 'rtvideoroom_c',
        desc: 'rtvideoroom api plugin',
        author: 'poplang',
        date: '2024-2-8',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtgift',
        path: 'plugins/rt-gift/index.js',
        url: './plugins/rt-gift/index.js',
        url_nodejs: './rt-gift/index.js',
        index: 'rtgift_c',
        desc: 'rtgift api plugin',
        author: 'poplang',
        date: '2024-2-7',
        nodejs: true,
        browser: true,
    },
    {
        name: 'rtphone',
        path: 'plugins/rt-phone/index.js',
        url: './plugins/rt-phone/index.js',
        url_nodejs: './rt-phone/index.js',
        index: 'rtphone_c',
        desc: 'rtphone api plugin',
        author: 'poplang',
        date: '2024-6-3',
        nodejs: true,
        browser: false,
    },
    {
        name:'rtpc',
        path:'plugins/rt-pc/index.js',
        url:'./plugins/rt-pc/index.js',
        url_nodejs:'./rt-pc/index.js',
        index:'rtpc_c',
        desc:'rtpc api plugin',
        author:'poplang',
        date:'2024-12-4',
        nodejs:false,
        browser:false,
    },
    {
        name:'rtturn',
        path:'plugins/rt-turn/index.js',
        url:'./plugins/rt-turn/index.js',
        url_nodejs:'./rt-turn/index.js',
        index:'rtturn_c',
        desc:'rtturn api plugin',
        author:'poplang',
        date:'2025-2-6',
        nodejs:true,
        browser:false,
    },
    {
        name: 'dtnsos',
        path: 'plugins/dtns-os/index.js',
        url: './plugins/dtns-os/index.js',
        url_nodejs: './dtns-os/index.js',
        index: 'dtnsos_c',
        desc: 'dtnsos api plugin',
        author: 'poplang',
        date: '2025-2-14',
        nodejs: true,
        browser: false,
    },
    {
        name: 'rtibchat',
        path: 'plugins/rt-ibchat/index.js',
        url: './plugins/rt-ibchat/index.js',
        url_nodejs: './rt-ibchat/index.js',
        index: 'rtibchat_c',
        desc: 'rtibchat api plugin',
        author: 'poplang',
        date: '2025-2-19',
        nodejs: true,
        browser: false,
    },
    {
        name: 'rtmailer',
        path: 'plugins/rt-mailer/index.js',
        url: './plugins/rt-mailer/index.js',
        url_nodejs: './rt-mailer/index.js',
        index: 'rtmailer_c',
        desc: 'rtmailer api plugin',
        author: 'poplang',
        date: '2025-3-27',
        nodejs: true,
        browser: false,
    },
    {
        name:'rtmailer',
        path:'plugins/rt-mailer/index.js',
        url:'./plugins/rt-mailer/index.js',
        url_nodejs:'./rt-mailer/index.js',
        index:'rtmailer_c',
        desc:'rtmailer api plugin',
        author:'poplang',
        date:'2025-3-27',
        nodejs:true,
        browser:false,
    },
    {
        name: 'rtmap',
        path: 'plugins/rt-map/index.js',
        url: './plugins/rt-map/index.js',
        url_nodejs: './rt-map/index.js',
        index: 'rtmap_c',
        desc: 'rtmap api plugin',
        author: 'poplang',
        date: '2025-3-29',
        nodejs: true,
        browser: false,
    },
    {
        name:'rtdatalink',
        path:'plugins/rt-datalink/index.js',
        url:'./plugins/rt-datalink/index.js',
        url_nodejs:'./rt-datalink/index.js',
        index:'rtdatalink_c',
        desc:'rtdatalink api plugin',
        author:'poplang',
        date:'2025-4-7',
        nodejs:true,
        browser:false,
    },
    {
        name:'rtkown',
        path:'plugins/rt-kown/index.js',
        url:'./plugins/rt-kown/index.js',
        url_nodejs:'./rt-kown/index.js',
        index:'rtkown_c',
        desc:'rtkown api plugin',
        author:'poplang',
        date:'2025-4-11',
        nodejs:true,
        browser:true,
    },
    {
        name:'rtibchat_manager',
        path:'plugins/rt-ibchat-manager/index.js',
        url:'./plugins/rt-ibchat-manager/index.js',
        url_nodejs:'./rt-ibchat-manager/index.js',
        index:'rtibchat_manager_c',
        desc:'rtibchat-manager api plugin',
        author:'poplang',
        date:'2025-4-21',
        nodejs:true,
        browser:false,
    }
]

